# Copyright (c) V-Nova International Limited 2024-2025. All rights reserved.
# This software is licensed under the BSD-3-Clause-Clear License by V-Nova Limited.
# No patent licenses are granted under this license. For enquiries about patent licenses,
# please contact legal@v-nova.com.
# The LCEVCdec software is a stand-alone project and is NOT A CONTRIBUTION to any other project.
# If the software is incorporated into another project, THE TERMS OF THE BSD-3-CLAUSE-CLEAR LICENSE
# AND THE ADDITIONAL LICENSING INFORMATION CONTAINED IN THIS FILE MUST BE MAINTAINED, AND THE
# SOFTWARE DOES NOT AND MUST NOT ADOPT THE LICENSE OF THE INCORPORATING PROJECT. However, the
# software may be incorporated into a project under a compatible license provided the requirements
# of the BSD-3-Clause-Clear license are respected, and V-Nova Limited remains
# licensor of the software ONLY UNDER the BSD-3-Clause-Clear license (not the compatible license).
# ANY ONWARD DISTRIBUTION, WHETHER STAND-ALONE OR AS PART OF ANY OTHER PROJECT, REMAINS SUBJECT TO
# THE EXCLUSION OF PATENT LICENSES PROVISION OF THE BSD-3-CLAUSE-CLEAR LICENSE.

name: Bug Report
description: Report a bug in the project
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please use this form to report a bug. Provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Briefly describe the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: |
        1. Link to bitstream/ upload the bitstream after create bug in the comments
        2. Decoder params required(harness command line OR configuration parameters)
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Observed Behavior
      description: Describe what actually happened.
      placeholder: Describe the actual behavior and attach screenshot of bad frame (again in comments if required)
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Fill out the following details about your system or device:
  - type: input
    id: os_desktop
    attributes:
      label: Operating System
      description: Specify your OS (e.g., Android, iOS, Windows, Linux).
      placeholder: e.g., iOS
  - type: input
    id: build_config
    attributes:
      label: Build Configuration
      description: Specify the SIMD, API version on Android.
      placeholder: e.g., api26
  - type: input
    id: dec_library
    attributes:
      label: Library details
      description: Details about library integrated or downstream projects
      placeholder: e.g., lcevc_dec_api.so
  - type: input
    id: device_name
    attributes:
      label: Device OS
      description: Specify the device OS (e.g., iOS 11, Android 10).
      placeholder: e.g., iOS11
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Provide any other relevant information.
      placeholder: Add any additional details
